Warning: "SET client_encoding" statement ignored in line 8
Warning: "SET client_encoding" statement ignored in line 15
Warning: "SET client_encoding" statement ignored in line 21
Warning: COPY statement ignored in line 25
Warning: fast-path function call ignored in line 49
Warning: fast-path function call ignored in line 50
Warning: fast-path function call ignored in line 51
Warning: fast-path function call ignored in line 52
Warning: fast-path function call ignored in line 54
