Warning: "SET client_encoding" statement ignored in line 7
Warning: "SET client_encoding" statement ignored in line 9
Warning: "SET client_encoding" statement ignored in line 19
Warning: COPY statement ignored in line 22
Warning: fast-path function call ignored in line 40
Warning: fast-path function call ignored in line 41
Warning: fast-path function call ignored in line 42
Warning: fast-path function call ignored in line 43
Warning: fast-path function call ignored in line 45
